# Generated by Django 5.0.4 on 2024-04-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_alter_flights_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='city',
            new_name='place',
        ),
    ]
